### ISSUE TITLE
希望模型加载拆成独立节点，方便在一个流中多次使用相同节点能够共享模型，以减少内存和显存占用

### ISSUE THREAD

**Issue by lldacing** [chflame163/ComfyUI_LayerStyle_Advance#13]
当前大部分节点的模式是模型和图片处理在一个节点，不利于在一个流程中有多个相同的节点的使用场景，因为模型会加载多次，虽然提供了cache_model选项，但是这个选项只能做到重复执行不加载，并不能做到节点间共享模型。

拿抠图简单举个例子，下面有两个抠图，模型相同，只是扣的部位不同，模型加载了两遍（看时间）
![image](https://github.com/user-attachments/assets/5075657e-c271-48e2-b0da-7da5a6e87068)

**Comment by chflame163** [comment]
SegmentAnythingUltraV3 and LoadSegmentAnythingModels nodes commited.

**Comment by lldacing** [comment]
> SegmentAnythingUltraV3 and LoadSegmentAnythingModels nodes commited.

没搜到，你是不是忘了提交python代码了，看提交记录里面没有相关代码提交

**Comment by chflame163** [comment]
> 没搜到，你是不是忘了提交python代码了，看提交记录里面没有相关代码提交

是的，现在更新上去了
