### ISSUE TITLE
更新了今天的新版的插件以后i就无法加载了

### ISSUE THREAD

**Issue by WhiteCrowLX** [chflame163/ComfyUI_LayerStyle_Advance#15]
双击repair_dependency.bat文件 提示的是 
D:\ComfyUI\custom_nodes\ComfyUI_LayerStyle_Advance>.\repair_dependency.bat
Fixing Dependency Package...
Installing with ComfyUI Portable
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Press any key to continue . . .
大神,请问怎么解决?已经试过重装,也无法解决,在这之前一直可以正常使用的.

**Comment by chflame163** [comment]
再更新一下试试
