### ISSUE TITLE
SAM2Ultra

### ISSUE THREAD

**Issue by Amazon90** [chflame163/ComfyUI_LayerStyle_Advance#3]
When I use the SAM2Ultra node, it automatically downloads the `models--hustvl--vitmatte-small-composition-1k` to the `.cache\huggingface` cache directory. If I don’t want it to be stored in the cache directory, where should I place the 'config.json', 'model.safetensors', and 'preprocessor_config.json' files in the `ComfyUI\models` folder? I have read the readme in your repository, but there is no mention of this issue.

**Comment by chflame163** [comment]
This section is missing from the Readme:    

>Some nodes named "Ultra" will use the vitmatte model, download the [vitmatte model](https://huggingface.co/hustvl/vitmatte-small-composition-1k/tree/main) and copy to ComfyUI/models/vitmatte folder, it is also included in the download link above.

**Comment by Amazon90** [comment]
> This section is missing from the Readme:
> 
> > Some nodes named "Ultra" will use the vitmatte model, download the [vitmatte model](https://huggingface.co/hustvl/vitmatte-small-composition-1k/tree/main) and copy to ComfyUI/models/vitmatte folder, it is also included in the download link above.

It’s strange—I’ve already downloaded these three files and placed them in the `ComfyUI\models\vitmatte` folder, but when running the Ultra node, it still tries to download them to the `ComfyUI\.cache\huggingface` cache directory.

**Comment by chflame163** [comment]
> It’s strange—I’ve already downloaded these three files and placed them in the `ComfyUI\models\vitmatte` folder, but when running the Ultra node, it still tries to download them to the `ComfyUI\.cache\huggingface` cache directory.

There are indeed some issues with the model loading code, which have been fixed. Please update and try again

**Comment by Amazon90** [comment]
> > It’s strange—I’ve already downloaded these three files and placed them in the `ComfyUI\models\vitmatte` folder, but when running the Ultra node, it still tries to download them to the `ComfyUI\.cache\huggingface` cache directory.
> 
> There are indeed some issues with the model loading code, which have been fixed. Please update and try again

Thank you, the issue has been fixed.
